// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc26TTpGWCjrg2ebMzfe_eaGwmRBtyjfw',
    appId: '1:720160639395:web:5c3bc73d0d2c2ff4917216',
    messagingSenderId: '720160639395',
    projectId: 'pragmatic-2e3e7',
    authDomain: 'pragmatic-2e3e7.firebaseapp.com',
    storageBucket: 'pragmatic-2e3e7.firebasestorage.app',
    measurementId: 'G-JDEZMC0CBJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTRba4I3B_rDTJNEj_w8-T5xZKeEV-95s',
    appId: '1:720160639395:android:b14448f0027888fe917216',
    messagingSenderId: '720160639395',
    projectId: 'pragmatic-2e3e7',
    storageBucket: 'pragmatic-2e3e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE-Zv1VdWeA8L1bF9fDeA4vTowHWXhZRI',
    appId: '1:720160639395:ios:5b5fd38fb1d878fa917216',
    messagingSenderId: '720160639395',
    projectId: 'pragmatic-2e3e7',
    storageBucket: 'pragmatic-2e3e7.firebasestorage.app',
    iosBundleId: 'com.example.pragmatic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE-Zv1VdWeA8L1bF9fDeA4vTowHWXhZRI',
    appId: '1:720160639395:ios:5b5fd38fb1d878fa917216',
    messagingSenderId: '720160639395',
    projectId: 'pragmatic-2e3e7',
    storageBucket: 'pragmatic-2e3e7.firebasestorage.app',
    iosBundleId: 'com.example.pragmatic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc26TTpGWCjrg2ebMzfe_eaGwmRBtyjfw',
    appId: '1:720160639395:web:1f2a8182b9c91727917216',
    messagingSenderId: '720160639395',
    projectId: 'pragmatic-2e3e7',
    authDomain: 'pragmatic-2e3e7.firebaseapp.com',
    storageBucket: 'pragmatic-2e3e7.firebasestorage.app',
    measurementId: 'G-FJJ1QZDGWG',
  );
}
